import React from 'react'
import Head from 'next/head'
import GameTracker from '../components/GameTracker'
import { Grid } from '@material-ui/core'
import styles from '../styles/Home.module.css'

const Main = () => {
    return (
        <main className={styles.main}>
            <Head>
                <title>{ process?.env?.NEXT_PUBLIC_APP_NAME ?? "MY TRACKER" }</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/apex-favicon.ico" />
            </Head>
            <br />
            <Grid container spacing={2}>
                <Grid item xs={2}>
                    
                </Grid>
                <Grid item xs={8}>
                    <GameTracker />
                    
                </Grid>
                <Grid item xs={2}>
                    
                </Grid>
            </Grid>
            <br />
        </main>
    )
}

export default Main
