import React from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Card ,CardContent, Button,Typography, Grid, FormControl, TextField, Select, InputLabel, MenuItem } from '@material-ui/core'
import { useState, useEffect } from 'react'

const Main = () => {
    const [enableSubmit, setEnableSubmit] = useState(false)
    const [game, setGame] = useState("")
    const [platform, setPlatform] = useState("")
    const [input, setInput] = useState("")
    const platformOptions = [
        {
            id: '1',
            name: 'PC',
            value: 'pc'
        },
        {
            id: '2',
            name: 'PSN',
            value: 'psn'
        },
        {
            id: '3',
            name: 'Xbox',
            value: 'xbox'
        }
    ]
    const gameOptions = [
        {
            id : 1,
            name : 'Apex Legends',
            value : 'Apex Legends'
        },
        {
            id : 2,
            name : 'Overwatch',
            value : 'Overwatch'
        }
    ]
    const handleGameChange = (event) => {
        setGame(event.target.value)
    }
    const handlePlatformChange = (event) => {
        setPlatform(event.target.value)
    }
    const handleInputChange = (event) => {
        setInput(event.target.value)
    }
    const handleClearButton = () => {
        setEnableSubmit(false)
        setGame("")
        setPlatform("")
        setInput("")
    }
    const handleSubmitButton = () => {

    }
    useEffect(() => {
        setEnableSubmit( game !== "" && platform !== "" && input !== "" )
    }, [game, platform, input])
    return (
        <main className={styles.main}>
            <div className={styles.container}>
                <Head>
                    <title>{ process?.env?.NEXT_PUBLIC_APP_NAME ?? "MY TRACKER" }</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/apex-favicon.ico" />
                </Head>
                <Grid container spacing={2}>
                    <Grid container spacing={2}>
                        <Grid item xs={12}>
                            <InputLabel required>Select a game</InputLabel>
                            <Select
                            id="a"
                            value={game}
                            onChange={handleGameChange}
                            fullWidth
                            >
                                { gameOptions.map( (item) => <MenuItem key={item.id} value={item.value}>{item.name}</MenuItem>) }
                            </Select>
                        </Grid>
                        <Grid item xs={12}>
                            <InputLabel required>Select a platform</InputLabel>
                            <Select
                            id="b"
                            value={platform}
                            onChange={handlePlatformChange}
                            fullWidth
                            >
                                { platformOptions.map( (item) => <MenuItem key={item.id} value={item.value}>{item.name}</MenuItem>) }
                            </Select>
                        </Grid>
                        <Grid item xs={12}>
                            <InputLabel required>Input your id</InputLabel>
                            <TextField
                            value={input}
                            onChange={handleInputChange}
                            inputProps={{min: 0, style: { textAlign: 'center' }}}
                            fullWidth
                            >

                            </TextField>
                        </Grid>
                        <Grid item xs={12}>
                            <Button variant="contained" color="default" style={{marginRight: '20px'}} onClick={handleClearButton}>
                                Clear
                            </Button>
                            <Button disabled={!enableSubmit} variant="contained" color="primary" onClick={handleSubmitButton}>
                                Submit
                            </Button>
                        </Grid>
                        {
                            game !== "" &&
                            <Grid item xs={12}>
                                <Typography>
                                    Your selected game is {game}
                                </Typography>
                            </Grid>
                        }
                        {
                            platform !== "" &&
                            <Grid item xs={12}>
                                <Typography>
                                    Your selected platform is {platform}
                                </Typography>
                            </Grid>
                        }
                        {
                            input !== "" &&
                            <Grid item xs={12}>
                                <Typography>
                                    Your selected input is {input}
                                </Typography>
                            </Grid>
                        }
                    </Grid>
                </Grid>
            </div>
        </main>
    )
}

export default Main
